name: Build Typst document

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README*.md
      - LICENSE
      - .github/**
      - "!.github/workflows/test-action.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Typst documents
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            main.typ

      - name: Upload generated PDF files
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: "*.pdf"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "*.pdf"
